-- MySQL Script generated by MySQL Workbench
-- Tue Dec 10 09:38:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fisica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fisica` (
  `idPessoaFisica` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `dataDeNasc` VARCHAR(45) NOT NULL,
  `sexo` ENUM('masculino', 'feminino') NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoaFisica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`juridica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`juridica` (
  `idPessoaJuridica` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(45) NOT NULL,
  `razao` VARCHAR(45) NOT NULL,
  `fantasia` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoaJuridica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `fisica_idPessoaFisica` INT NULL,
  `juridica_idPessoaJuridica` INT NULL,
  `nome` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEndereco`),
  CONSTRAINT `fk_endereco_fisica1`
    FOREIGN KEY (`fisica_idPessoaFisica`)
    REFERENCES `mydb`.`fisica` (`idPessoaFisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_juridica1`
    FOREIGN KEY (`juridica_idPessoaJuridica`)
    REFERENCES `mydb`.`juridica` (`idPessoaJuridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_endereco_fisica1_idx` ON `mydb`.`endereco` (`fisica_idPessoaFisica` ASC) VISIBLE;

CREATE INDEX `fk_endereco_juridica1_idx` ON `mydb`.`endereco` (`juridica_idPessoaJuridica` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`juridica_has_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`juridica_has_pessoa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`juridica_has_pessoa` (
  `juridica_idPessoaJuridica` INT NOT NULL,
  `pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`juridica_idPessoaJuridica`, `pessoa_idPessoa`),
  CONSTRAINT `fk_juridica_has_pessoa_juridica`
    FOREIGN KEY (`juridica_idPessoaJuridica`)
    REFERENCES `mydb`.`juridica` (`idPessoaJuridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_juridica_has_pessoa_pessoa1`
    FOREIGN KEY (`pessoa_idPessoa`)
    REFERENCES `mydb`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_juridica_has_pessoa_pessoa1_idx` ON `mydb`.`juridica_has_pessoa` (`pessoa_idPessoa` ASC) VISIBLE;

CREATE INDEX `fk_juridica_has_pessoa_juridica_idx` ON `mydb`.`juridica_has_pessoa` (`juridica_idPessoaJuridica` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`fisica_has_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fisica_has_pessoa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fisica_has_pessoa` (
  `fisica_idPessoaFisica` INT NOT NULL,
  `pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`fisica_idPessoaFisica`, `pessoa_idPessoa`),
  CONSTRAINT `fk_fisica_has_pessoa_fisica1`
    FOREIGN KEY (`fisica_idPessoaFisica`)
    REFERENCES `mydb`.`fisica` (`idPessoaFisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fisica_has_pessoa_pessoa1`
    FOREIGN KEY (`pessoa_idPessoa`)
    REFERENCES `mydb`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_fisica_has_pessoa_pessoa1_idx` ON `mydb`.`fisica_has_pessoa` (`pessoa_idPessoa` ASC) VISIBLE;

CREATE INDEX `fk_fisica_has_pessoa_fisica1_idx` ON `mydb`.`fisica_has_pessoa` (`fisica_idPessoaFisica` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`pessoa`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`pessoa` (`idPessoa`) VALUES (1);
INSERT INTO `mydb`.`pessoa` (`idPessoa`) VALUES (2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`fisica`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`fisica` (`idPessoaFisica`, `Nome`, `cpf`, `dataDeNasc`, `sexo`, `email`) VALUES (1, 'Sergio', '07234087346', '19/03/1998', 'masculino', 'sergio@outlook.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`juridica`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`juridica` (`idPessoaJuridica`, `cnpj`, `razao`, `fantasia`, `email`) VALUES (1, '27.865.757/0001-02', 'GLOBO', 'GLOBO', 'globo@email.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`endereco`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`endereco` (`idEndereco`, `fisica_idPessoaFisica`, `juridica_idPessoaJuridica`, `nome`, `logradouro`, `bairro`, `numero`, `cidade`, `estado`, `CEP`) VALUES (1, NULL, NULL, 'casa', 'Rua A', 'Cajazeira', '52', 'Fortaleza', 'Ceara', '60864463');
INSERT INTO `mydb`.`endereco` (`idEndereco`, `fisica_idPessoaFisica`, `juridica_idPessoaJuridica`, `nome`, `logradouro`, `bairro`, `numero`, `cidade`, `estado`, `CEP`) VALUES (2, NULL, NULL, 'sede', 'Avenida Copacabana', 'Ipanema', '234', 'Rio de Janeiro', 'Rio de Janeiro', '123456');

COMMIT;

