-- MySQL Script generated by MySQL Workbench
-- Fri Dec 20 08:50:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alana486_testeProjeto2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `alana486_testeProjeto2` ;

-- -----------------------------------------------------
-- Schema alana486_testeProjeto2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alana486_testeProjeto2` DEFAULT CHARACTER SET utf8 ;
USE `alana486_testeProjeto2` ;

-- -----------------------------------------------------
-- Table `alana486_testeProjeto2`.`contato_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alana486_testeProjeto2`.`contato_juridica` ;

CREATE TABLE IF NOT EXISTS `alana486_testeProjeto2`.`contato_juridica` (
  `idcontato_juridica` INT NOT NULL AUTO_INCREMENT,
  `nomeResp` VARCHAR(45) NOT NULL,
  `setor` VARCHAR(45) NOT NULL,
  `juridica_id_juridica` INT NOT NULL,
  PRIMARY KEY (`idcontato_juridica`),
  CONSTRAINT `fk_contao_juridica1`
    FOREIGN KEY (`juridica_id_juridica`)
    REFERENCES `alana486_testeProjeto2`.`juridica` (`id_juridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_contao_juridica1_idx` ON `alana486_testeProjeto2`.`contato_juridica` (`juridica_id_juridica` ASC) ;

CREATE UNIQUE INDEX `nomeResp_UNIQUE` ON `alana486_testeProjeto2`.`contato_juridica` (`nomeResp` ASC) ;


-- -----------------------------------------------------
-- Table `alana486_testeProjeto2`.`email_contato_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alana486_testeProjeto2`.`email_contato_juridica` ;

CREATE TABLE IF NOT EXISTS `alana486_testeProjeto2`.`email_contato_juridica` (
  `idemail_contato_juridica` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `contato_idcontato` INT NOT NULL,
  PRIMARY KEY (`idemail_contato_juridica`),
  CONSTRAINT `fk_email_contato1`
    FOREIGN KEY (`contato_idcontato`)
    REFERENCES `alana486_testeProjeto2`.`contato_juridica` (`idcontato_juridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_email_contato1_idx` ON `alana486_testeProjeto2`.`email_contato_juridica` (`contato_idcontato` ASC) ;


-- -----------------------------------------------------
-- Table `alana486_testeProjeto2`.`email_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alana486_testeProjeto2`.`email_juridica` ;

CREATE TABLE IF NOT EXISTS `alana486_testeProjeto2`.`email_juridica` (
  `idemail` INT NOT NULL AUTO_INCREMENT,
  `email_juridica` VARCHAR(45) NOT NULL,
  `juridica_id_juridica` INT NOT NULL,
  PRIMARY KEY (`idemail`),
  CONSTRAINT `fk_email_juridica_juridica1`
    FOREIGN KEY (`juridica_id_juridica`)
    REFERENCES `alana486_testeProjeto2`.`juridica` (`id_juridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_email_juridica_juridica1_idx` ON `alana486_testeProjeto2`.`email_juridica` (`juridica_id_juridica` ASC) ;


-- -----------------------------------------------------
-- Table `alana486_testeProjeto2`.`endereco_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alana486_testeProjeto2`.`endereco_juridica` ;

CREATE TABLE IF NOT EXISTS `alana486_testeProjeto2`.`endereco_juridica` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `juridica_id_juridica` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  CONSTRAINT `fk_endereco_juridica10`
    FOREIGN KEY (`juridica_id_juridica`)
    REFERENCES `alana486_testeProjeto2`.`juridica` (`id_juridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idEndereco_UNIQUE` ON `alana486_testeProjeto2`.`endereco_juridica` (`idEndereco` ASC) ;

CREATE INDEX `fk_endereco_juridica1_idx` ON `alana486_testeProjeto2`.`endereco_juridica` (`juridica_id_juridica` ASC) ;


-- -----------------------------------------------------
-- Table `alana486_testeProjeto2`.`endereco_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alana486_testeProjeto2`.`endereco_pessoa` ;

CREATE TABLE IF NOT EXISTS `alana486_testeProjeto2`.`endereco_pessoa` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  CONSTRAINT `fk_endereco_pessoa_pessoa1`
    FOREIGN KEY (`pessoa_idPessoa`)
    REFERENCES `alana486_testeProjeto2`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idEndereco_UNIQUE` ON `alana486_testeProjeto2`.`endereco_pessoa` (`idEndereco` ASC) ;

CREATE INDEX `fk_endereco_pessoa_pessoa1_idx` ON `alana486_testeProjeto2`.`endereco_pessoa` (`pessoa_idPessoa` ASC) ;


-- -----------------------------------------------------
-- Table `alana486_testeProjeto2`.`juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alana486_testeProjeto2`.`juridica` ;

CREATE TABLE IF NOT EXISTS `alana486_testeProjeto2`.`juridica` (
  `id_juridica` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(45) NOT NULL,
  `razao` VARCHAR(45) NOT NULL,
  `fantasia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_juridica`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cnpj_UNIQUE` ON `alana486_testeProjeto2`.`juridica` (`cnpj` ASC) ;

CREATE UNIQUE INDEX `razao_UNIQUE` ON `alana486_testeProjeto2`.`juridica` (`razao` ASC) ;


-- -----------------------------------------------------
-- Table `alana486_testeProjeto2`.`juridica_has_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alana486_testeProjeto2`.`juridica_has_pessoa` ;

CREATE TABLE IF NOT EXISTS `alana486_testeProjeto2`.`juridica_has_pessoa` (
  `juridica_id_juridica` INT NOT NULL,
  `pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`juridica_id_juridica`, `pessoa_idPessoa`),
  CONSTRAINT `fk_juridica_has_pessoa_juridica1`
    FOREIGN KEY (`juridica_id_juridica`)
    REFERENCES `alana486_testeProjeto2`.`juridica` (`id_juridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_juridica_has_pessoa_pessoa1`
    FOREIGN KEY (`pessoa_idPessoa`)
    REFERENCES `alana486_testeProjeto2`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_juridica_has_pessoa_pessoa1_idx` ON `alana486_testeProjeto2`.`juridica_has_pessoa` (`pessoa_idPessoa` ASC) ;

CREATE INDEX `fk_juridica_has_pessoa_juridica1_idx` ON `alana486_testeProjeto2`.`juridica_has_pessoa` (`juridica_id_juridica` ASC) ;


-- -----------------------------------------------------
-- Table `alana486_testeProjeto2`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alana486_testeProjeto2`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `alana486_testeProjeto2`.`pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `dataDeNasc` VARCHAR(45) NOT NULL,
  `sexo` ENUM('masculino', 'feminino') NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cpf_UNIQUE` ON `alana486_testeProjeto2`.`pessoa` (`cpf` ASC) ;

CREATE UNIQUE INDEX `idPessoaFisica_UNIQUE` ON `alana486_testeProjeto2`.`pessoa` (`idPessoa` ASC) ;


-- -----------------------------------------------------
-- Table `alana486_testeProjeto2`.`telefone_contato_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alana486_testeProjeto2`.`telefone_contato_juridica` ;

CREATE TABLE IF NOT EXISTS `alana486_testeProjeto2`.`telefone_contato_juridica` (
  `idtelefone_contato_juridica` INT NOT NULL AUTO_INCREMENT,
  `telefone_contato_juridica` VARCHAR(45) NOT NULL,
  `contato_idcontato` INT NOT NULL,
  PRIMARY KEY (`idtelefone_contato_juridica`),
  CONSTRAINT `fk_telefone_contato_juridica_contato1`
    FOREIGN KEY (`contato_idcontato`)
    REFERENCES `alana486_testeProjeto2`.`contato_juridica` (`idcontato_juridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_telefone_contato_juridica_contato1_idx` ON `alana486_testeProjeto2`.`telefone_contato_juridica` (`contato_idcontato` ASC) ;


-- -----------------------------------------------------
-- Table `alana486_testeProjeto2`.`telefone_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alana486_testeProjeto2`.`telefone_juridica` ;

CREATE TABLE IF NOT EXISTS `alana486_testeProjeto2`.`telefone_juridica` (
  `id_telefone_juridica` INT NOT NULL AUTO_INCREMENT,
  `telefone_juridica` VARCHAR(45) NOT NULL,
  `juridica_id_juridica` INT NOT NULL,
  PRIMARY KEY (`id_telefone_juridica`),
  CONSTRAINT `fk_telefone_juridica_juridica1`
    FOREIGN KEY (`juridica_id_juridica`)
    REFERENCES `alana486_testeProjeto2`.`juridica` (`id_juridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_telefone_juridica_juridica1_idx` ON `alana486_testeProjeto2`.`telefone_juridica` (`juridica_id_juridica` ASC) ;


-- -----------------------------------------------------
-- Table `alana486_testeProjeto2`.`telefone_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alana486_testeProjeto2`.`telefone_pessoa` ;

CREATE TABLE IF NOT EXISTS `alana486_testeProjeto2`.`telefone_pessoa` (
  `id_telefone_pessoa` INT NOT NULL AUTO_INCREMENT,
  `telefone_pessoa` VARCHAR(45) NOT NULL,
  `pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`id_telefone_pessoa`),
  CONSTRAINT `fk_telefone_pessoa_pessoa1`
    FOREIGN KEY (`pessoa_idPessoa`)
    REFERENCES `alana486_testeProjeto2`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_telefone_pessoa_pessoa1_idx` ON `alana486_testeProjeto2`.`telefone_pessoa` (`pessoa_idPessoa` ASC) ;


-- -----------------------------------------------------
-- Table `alana486_testeProjeto2`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alana486_testeProjeto2`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `alana486_testeProjeto2`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nivel` INT NULL,
  `ativo` INT NULL,
  `cadastro` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `usuario_UNIQUE` ON `alana486_testeProjeto2`.`usuarios` (`usuario` ASC) ;

CREATE UNIQUE INDEX `email_UNIQUE` ON `alana486_testeProjeto2`.`usuarios` (`email` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `alana486_testeProjeto2`.`contato_juridica`
-- -----------------------------------------------------
START TRANSACTION;
USE `alana486_testeProjeto2`;
INSERT INTO `alana486_testeProjeto2`.`contato_juridica` (`idcontato_juridica`, `nomeResp`, `setor`, `juridica_id_juridica`) VALUES (1, 'Sergio', 'Financeiro', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `alana486_testeProjeto2`.`email_contato_juridica`
-- -----------------------------------------------------
START TRANSACTION;
USE `alana486_testeProjeto2`;
INSERT INTO `alana486_testeProjeto2`.`email_contato_juridica` (`idemail_contato_juridica`, `email`, `contato_idcontato`) VALUES (1, 'sergio.s.neto@outlook.com', 1);
INSERT INTO `alana486_testeProjeto2`.`email_contato_juridica` (`idemail_contato_juridica`, `email`, `contato_idcontato`) VALUES (2, 'sergio.s.neto2@outlook.com', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `alana486_testeProjeto2`.`email_juridica`
-- -----------------------------------------------------
START TRANSACTION;
USE `alana486_testeProjeto2`;
INSERT INTO `alana486_testeProjeto2`.`email_juridica` (`idemail`, `email_juridica`, `juridica_id_juridica`) VALUES (1, 'globo@email.com', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `alana486_testeProjeto2`.`endereco_juridica`
-- -----------------------------------------------------
START TRANSACTION;
USE `alana486_testeProjeto2`;
INSERT INTO `alana486_testeProjeto2`.`endereco_juridica` (`idEndereco`, `nome`, `logradouro`, `bairro`, `numero`, `cidade`, `estado`, `CEP`, `juridica_id_juridica`) VALUES (1, 'casa', 'rua lucia saboia', 'Centro', '234', 'Sobral', 'Ceara', '48873345', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `alana486_testeProjeto2`.`endereco_pessoa`
-- -----------------------------------------------------
START TRANSACTION;
USE `alana486_testeProjeto2`;
INSERT INTO `alana486_testeProjeto2`.`endereco_pessoa` (`idEndereco`, `nome`, `logradouro`, `bairro`, `numero`, `cidade`, `estado`, `CEP`, `pessoa_idPessoa`) VALUES (1, 'casa', 'Rua A', 'Cajazeira', '52', 'Fortaleza', 'Ceara', '60864463', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `alana486_testeProjeto2`.`juridica`
-- -----------------------------------------------------
START TRANSACTION;
USE `alana486_testeProjeto2`;
INSERT INTO `alana486_testeProjeto2`.`juridica` (`id_juridica`, `cnpj`, `razao`, `fantasia`) VALUES (1, '27.865.757/0001-02', 'GLOBO', 'GLOBO');

COMMIT;


-- -----------------------------------------------------
-- Data for table `alana486_testeProjeto2`.`juridica_has_pessoa`
-- -----------------------------------------------------
START TRANSACTION;
USE `alana486_testeProjeto2`;
INSERT INTO `alana486_testeProjeto2`.`juridica_has_pessoa` (`juridica_id_juridica`, `pessoa_idPessoa`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `alana486_testeProjeto2`.`pessoa`
-- -----------------------------------------------------
START TRANSACTION;
USE `alana486_testeProjeto2`;
INSERT INTO `alana486_testeProjeto2`.`pessoa` (`idPessoa`, `Nome`, `cpf`, `dataDeNasc`, `sexo`, `email`) VALUES (1, 'Sergio', '07234087346', '19/03/1998', 'masculino', 'sergio@outlook.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `alana486_testeProjeto2`.`telefone_contato_juridica`
-- -----------------------------------------------------
START TRANSACTION;
USE `alana486_testeProjeto2`;
INSERT INTO `alana486_testeProjeto2`.`telefone_contato_juridica` (`idtelefone_contato_juridica`, `telefone_contato_juridica`, `contato_idcontato`) VALUES (1, '85997246598', 1);
INSERT INTO `alana486_testeProjeto2`.`telefone_contato_juridica` (`idtelefone_contato_juridica`, `telefone_contato_juridica`, `contato_idcontato`) VALUES (2, '85988763456', 1);
INSERT INTO `alana486_testeProjeto2`.`telefone_contato_juridica` (`idtelefone_contato_juridica`, `telefone_contato_juridica`, `contato_idcontato`) VALUES (3, '88976345212', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `alana486_testeProjeto2`.`telefone_juridica`
-- -----------------------------------------------------
START TRANSACTION;
USE `alana486_testeProjeto2`;
INSERT INTO `alana486_testeProjeto2`.`telefone_juridica` (`id_telefone_juridica`, `telefone_juridica`, `juridica_id_juridica`) VALUES (1, '8532891471', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `alana486_testeProjeto2`.`telefone_pessoa`
-- -----------------------------------------------------
START TRANSACTION;
USE `alana486_testeProjeto2`;
INSERT INTO `alana486_testeProjeto2`.`telefone_pessoa` (`id_telefone_pessoa`, `telefone_pessoa`, `pessoa_idPessoa`) VALUES (1, '85997246598', 1);

COMMIT;

